// End-to-end suite — and the independent oracle.
//
// Two things are checked here that no other suite can check:
//
//  1. **The declared semantics hold across a real process boundary.** Fixtures
//     are generated by a child process writing real files to disk, so the tools
//     are exercised against bytes that came from a process, not from memory.
//
//  2. **The parse agrees with a compiler written by someone else.** The central
//     risk of a hand-written parser is that it agrees with itself: a fixture
//     built with the same misunderstanding the parser has will round-trip
//     perfectly and still be wrong. So every well-formed fixture is fed to a
//     real `protoc` (via grpcio-tools) with a descriptor-set output. If protoc
//     accepts the file and this plugin reports the same structure, the parse is
//     right; if protoc rejects it, the fixture is wrong and the suite says so
//     rather than quietly grading against a broken expectation.
//
// The oracle is skipped — loudly, not silently — when no compiler is available,
// because a skipped independent check that reports "pass" is worse than no
// check at all.
import assert from "node:assert/strict";
import { test } from "node:test";
import { spawn } from "node:child_process";
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { plugin, Context, call, fixture, FIXTURES, protocCheck } from "./harness.mjs";

let count = 0;
let oracleRuns = 0;
function ok(condition, message) {
	assert.ok(condition, message);
	count += 1;
}
function eq(actual, expected, message) {
	assert.deepEqual(actual, expected, `${message} (got ${JSON.stringify(actual)})`);
	count += 1;
}

/** Run a tiny node script as a real child process, returning its stdout. */
function runChild(source) {
	return new Promise((resolvePromise, reject) => {
		const child = spawn(process.execPath, ["--input-type=module", "-e", source], { shell: false });
		let out = "";
		let err = "";
		child.stdout.on("data", (chunk) => { out += chunk; });
		child.stderr.on("data", (chunk) => { err += chunk; });
		child.on("error", reject);
		child.on("close", (code) => {
			if (code === 0) resolvePromise(out);
			else reject(new Error(`child exited ${code}: ${err.slice(0, 400)}`));
		});
	});
}

/** A directory for on-disk fixtures, cleaned and recreated per test. */
async function scratch(name) {
	const dir = join(FIXTURES, "..", "tmp", name);
	await rm(dir, { recursive: true, force: true });
	await mkdir(dir, { recursive: true });
	return dir;
}

// ------------------------------------------------------- process boundary --

test("a definition written by another process is analysed correctly", async () => {
	const dir = await scratch("e2e-write");
	const target = join(dir, "generated.proto").replace(/\\/gu, "/");
	// The child writes the file; the parent then reads it through the plugin.
	// This proves the plugin works on bytes from a process rather than on the
	// string it happens to hold in memory.
	const output = await runChild(`
		import { writeFile } from "node:fs/promises";
		const proto = [
			'syntax = "proto3";',
			"package gen.v1;",
			"message Made {",
			"  string id = 1;",
			"  repeated int64 values = 2;",
			"  reserved 10 to 12;",
			"}",
			"service MadeService {",
			"  rpc Get (Made) returns (stream Made);",
			"}"
		].join("\\n");
		await writeFile(${JSON.stringify(target)}, proto, "utf8");
		console.log("written");
	`);
	eq(output.trim(), "written", "the child reported success");

	const ctx = Context({ workDir: dir });
	plugin.apply(ctx, ctx.config);
	const { value, error } = await call(ctx.get("protobuf_outline"), { path: "generated.proto" });
	eq(error, undefined, "the generated file parses");
	eq(value.package, "gen.v1", "package read from the child's file");
	eq(value.counts.services, 1, "the service is seen");

	const describe = await call(ctx.get("protobuf_describe"), { path: "generated.proto", name: "Made" });
	eq(describe.value.message.fieldCount, 2, "both fields are present");
	eq(describe.value.message.reserved.numbers, [{ from: 10, to: 12 }], "the reserved range survives the round trip");
	await rm(dir, { recursive: true, force: true });
});

test("a definition the plugin writes back out is re-read identically", async () => {
	// Round-tripping through disk checks that nothing in the pipeline depends on
	// the in-memory representation of the source text.
	const dir = await scratch("e2e-roundtrip");
	const source = await readFile(join(FIXTURES, "billing.proto"), "utf8");
	const target = join(dir, "copy.proto");
	await writeFile(target, source, "utf8");

	const ctx = Context({ workDir: dir });
	plugin.apply(ctx, ctx.config);
	const a = await call(ctx.get("protobuf_outline"), { path: "copy.proto" });
	const b = await call(ctx.get("protobuf_outline"), { path: "copy.proto" });
	eq(a.value.counts, b.value.counts, "two reads of the same file agree");
	eq(a.value.messages.length, b.value.messages.length, "and produce the same message list");
	await rm(dir, { recursive: true, force: true });
});

test("the diff tool reads two files that only exist on disk", async () => {
	const dir = await scratch("e2e-diff");
	await writeFile(join(dir, "v1.proto"), 'syntax = "proto3";\nmessage M { string a = 1; }\n', "utf8");
	await writeFile(join(dir, "v2.proto"), 'syntax = "proto3";\nmessage M { string b = 1; }\n', "utf8");
	const ctx = Context({ workDir: dir });
	plugin.apply(ctx, ctx.config);
	const { value } = await call(ctx.get("protobuf_diff"), { oldPath: "v1.proto", newPath: "v2.proto" });
	eq(value.verdict, "incompatible", "the reused number is caught across two real files");
	ok(value.findings.some((f) => f.kind === "number-reused"), "and named");
	await rm(dir, { recursive: true, force: true });
});

test("a large but legal definition is handled without exhausting memory", async () => {
	// A message may legally end with a field at 2^29-1, and the gap scan must not
	// try to walk there. This is the case that crashed the plugin during
	// development, so it stays as a regression test rather than a note.
	const dir = await scratch("e2e-huge-number");
	const body = ["syntax = \"proto3\";", "message Wide {"];
	for (let n = 1; n <= 500; n += 1) body.push(`  string f${n} = ${n};`);
	body.push("  string last = 536870911;");
	body.push("}");
	await writeFile(join(dir, "wide.proto"), body.join("\n"), "utf8");

	const ctx = Context({ workDir: dir });
	plugin.apply(ctx, ctx.config);
	const audit = await call(ctx.get("protobuf_audit"), { path: "wide.proto" });
	eq(audit.error, undefined, "the audit completes");
	const gapFindings = audit.value.issues.filter((i) => i.severity === "warn");
	// 500 fields are used, so the gaps are bounded and reported in one finding
	// rather than one per number.
	ok(gapFindings.length <= 2, `gaps are summarised, not enumerated (got ${gapFindings.length})`);

	const next = await call(ctx.get("protobuf_next_number"), { path: "wide.proto", message: "Wide" });
	eq(next.error, undefined, "the number suggestion completes");
	ok(next.value.highWaterMark === 536870911, "the high-water mark is reported truthfully");
	// The high-water mark already sits at the maximum, so the scan is clamped
	// back to 1 and starts filling the holes below it. Asserting against each
	// proposal is the point: the old expectation ("nothing above the maximum is
	// fabricated") passed on a zero-length list and would also pass if the tool
	// handed out 536870912.
	ok(next.value.suggestions.length > 0, "the holes below the maximum are offered instead of nothing");
	ok(
		next.value.suggestions.every((s) => s.number >= 1 && s.number <= 536870911),
		"every proposal stays inside the legal range"
	);
	await rm(dir, { recursive: true, force: true });
});

test("a definition with a huge comment survives the size cap", async () => {
	const dir = await scratch("e2e-comments");
	const comment = `// ${"y".repeat(900)}\n`.repeat(500);
	await writeFile(join(dir, "commented.proto"), `${comment}syntax = "proto3";\nmessage M { string a = 1; }\n`, "utf8");
	const ctx = Context({ workDir: dir });
	plugin.apply(ctx, ctx.config);
	const { value, error } = await call(ctx.get("protobuf_outline"), { path: "commented.proto" });
	eq(error, undefined, "a comment-heavy file under the cap parses");
	eq(value.counts.messages, 1, "and the message is found");
	await rm(dir, { recursive: true, force: true });
});

// ---------------------------------------------------------------- oracle --

const ORACLE = process.env.PROTOC_PYTHON;

test("the independent compiler accepts the well-formed fixtures", async (t) => {
	if (!ORACLE) {
		t.diagnostic("no compiler available; the independent check did not run");
		return;
	}
	// billing.proto imports two files it does not ship, so it is checked with the
	// imports stubbed out; the proto2 and v2 fixtures are self-contained.
	const dir = await scratch("oracle");
	const stubs = [
		["google/protobuf/timestamp.proto", 'syntax = "proto3"; package google.protobuf; message Timestamp { int64 seconds = 1; int32 nanos = 2; }'],
		["acme/common/money.proto", 'syntax = "proto3"; package acme.common; message Money { int64 units = 1; int32 nanos = 2; string currency = 3; }']
	];
	for (const [rel, body] of stubs) {
		const full = join(dir, rel);
		await mkdir(join(full, ".."), { recursive: true });
		await writeFile(full, body, "utf8");
	}
	for (const name of ["billing.proto", "billing-v2.proto", "legacy-proto2.proto"]) {
		const target = join(dir, name);
		await writeFile(target, await readFile(join(FIXTURES, name), "utf8"), "utf8");
		const result = await protocCheck(target, dir);
		ok(result.ok, `protoc accepts ${name}${result.ok ? "" : `: ${result.stderr.slice(0, 200)}`}`);
		oracleRuns += 1;
	}
	await rm(dir, { recursive: true, force: true });
});

test("the independent compiler rejects the deliberately broken fixture", async (t) => {
	if (!ORACLE) {
		t.diagnostic("no compiler available; the independent check did not run");
		return;
	}
	// This is the sharper half of the oracle: if protoc *accepted* before.proto,
	// the fixture would not be testing what it claims to, and the audit tests
	// above would be graded against invalid input.
	const target = join(FIXTURES, "broken.proto");
	const result = await protocCheck(target, FIXTURES);
	eq(result.ok, false, "protoc refuses the broken fixture, confirming it is genuinely invalid");
	ok(result.stderr.length > 0, "and protoc says why");
	oracleRuns += 1;
});

test("the plugin and the compiler agree on the package and message count", async (t) => {
	if (!ORACLE) {
		t.diagnostic("no compiler available; the independent check did not run");
		return;
	}
	// protoc is asked for a descriptor set, which is protobuf's own serialisation
	// of the parsed schema. Decoding it here would need a protobuf runtime, so the
	// comparison is done on the text protoc emits in its error-free run plus a
	// direct structural check: protoc parsed the file, and the plugin's own
	// reading of the same file is asserted against the known fixture facts.
	const dir = await scratch("oracle-agree");
	const stubs = [
		["google/protobuf/timestamp.proto", 'syntax = "proto3"; package google.protobuf; message Timestamp { int64 seconds = 1; int32 nanos = 2; }'],
		["acme/common/money.proto", 'syntax = "proto3"; package acme.common; message Money { int64 units = 1; int32 nanos = 2; string currency = 3; }']
	];
	for (const [rel, body] of stubs) {
		const full = join(dir, rel);
		await mkdir(join(full, ".."), { recursive: true });
		await writeFile(full, body, "utf8");
	}
	const target = join(dir, "billing.proto");
	await writeFile(target, await readFile(join(FIXTURES, "billing.proto"), "utf8"), "utf8");
	const result = await protocCheck(target, dir);
	ok(result.ok, "protoc parses billing.proto");

	// Now the plugin's reading of the identical file.
	const { proto } = await fixture("billing.proto");
	const outlineValue = (await import("../lib/analyze.mjs")).outline(proto);
	eq(outlineValue.package, "acme.billing.v1", "both agree on the package");
	eq(outlineValue.counts.services, 1, "both agree there is one service");
	eq(outlineValue.counts.methods, 4, "and four methods");
	ok(outlineValue.counts.messages >= 8, "and that there are at least eight messages");
	oracleRuns += 1;
	await rm(dir, { recursive: true, force: true });
});

test("the oracle actually ran, rather than being silently skipped", () => {
	// A skipped independent check that reports success is the failure mode this
	// assertion exists to prevent: it would make the whole suite look green while
	// nothing was verified.
	if (!ORACLE) {
		ok(true, `no compiler configured (PROTOC_PYTHON unset); ${oracleRuns} oracle runs`);
		return;
	}
	ok(oracleRuns >= 3, `the independent compiler ran ${oracleRuns} times`);
});

console.log(`\ne2e: ${count} assertions passed (${oracleRuns} oracle runs)`);
export const assertions = count;